### ISSUE TITLE
Create gradle/maven projects for users to re-use when adding mysql driver to SCDF server

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow-samples#107]

**Comment by jvalkeal** [comment]
I've added a sample https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/custom-dataflow-builds/dataflow-server-21x to build atop of dataflow 2.1.2. We can then start adding newer versions when those are released.
