### ISSUE TITLE
Create a scheduling migration application for 2.3.x

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-samples#121]
Since we are changing the way how scheduling works in 2.3.x (a new scheduling-dataflow app + naming convention changes), we will have to create a migration app/tool to migrate the 2.1/2.2 users to 2.3.x easily.

**Acceptance:**
- This is required only for Cloud Foundry
- The app/tool will retrieve the existing schedules; it will then create the new schedules with the new naming conventions, and upon successful scheduling, delete the old schedules from the underlying platform
- Users can migrate from 2.x.x to 2.3.x without any manual intervention
- The app/tool can be used in an "errand" as part of the 2.3.x-based SCDF Tile upgrades (fyi: @mheath / @csterwa) 
- Host the app/tool in SCDF Samples repo

**Comment by cppwfs** [comment]
CF Migration Steps.
1A) Obtain list of schedules filtered by those that should not be converted (using a tag provided by a user).
1B) user should be able to give us a list of those to be converted.
2) For each element in the list
3) Obtain User Environment Variables and change them so they can be pass through.
4) Have to obtain command line args from the command :-(
5) Deploy new application
6) Create new Schedule
7) Delete old Schedule

**Comment by cppwfs** [comment]
K8 Migration Steps:
1A) Obtain list of schedules filtered by those that should not be converted (using a tag provided by a user).
1B) user should be able to give us a list of those to be converted.
2) For each element in the list
3) Obtain specification
3A) Get args
3B) where to get properties from specification
3C) Create new specification from original updating arguments so they can be pass through.
