### ISSUE TITLE
Migrate build from Bamboo to Github actions

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow-samples#155]
# Motivation
Bamboo is a legacy build system with a modern replacement of Github actions. This is the direction the SCDF builds are heading. 

# Steps
- [ ] **STEP1**: basic build/test w/ github actions
- [ ] **STEP2**: publish to artifactory w/ github actions
- [ ] **STEP3**: document how to use the above (gotchas, etc..)

# Step Details 

## STEP1
- Do the ~same thing as in [spring-shell/ci.yml|ci-pr.yml](https://github.com/spring-projects/spring-shell/tree/main/.github/workflows) 

## STEP2
- Do the ~same thing as in [spring-shell/ci-publish.yml](https://github.com/spring-projects/spring-shell/tree/main/.github/workflows)

**Comment by bono007** [comment]
cc: @cppwfs @jvalkeal
