### ISSUE TITLE
Unclear how to add timestamp-task and timestamp-batch-task as applications in SCDF 2.11.2

### ISSUE THREAD

**Issue by favna** [spring-cloud/spring-cloud-dataflow-samples#197]
Hi there,

When installing SCDF 2.11.2 I got the old [`maven://org.springframework.cloud.task.app:timestamp-task:2.0.2.RELEASE`](https://central.sonatype.com/artifact/org.springframework.cloud.task.app/timestamp-task) and [`maven://org.springframework.cloud.task.app:timestamp-batch-task:2.0.2.RELEASE`](https://central.sonatype.com/artifact/org.springframework.cloud.task.app/timestamp-batch-task) and I wanted to replace them with the newer versions in this repository because they leverage Spring Boot 3.x instead of 2.x for the old ones.

Problem is, I cannot find how to do this anywhere on this repository. I did find https://central.sonatype.com/artifact/io.spring.cloud/timestamp-task which seems to be a 1.0.0-RELEASE of the timestamp-task but whether that's Spring Boot 2.x or 3.x is unclear. I can also not find an equivalent for timestamp-batch-task (https://central.sonatype.com/artifact/io.spring.cloud/timestamp-batch-task does not exist)

Help would really be appreciated.

**Comment by corneil** [comment]
These applications are in repo.spring.io/milestone which is automatically added to the list repos
The maven coordinates are:

* `io.spring:timestamp-task:2.0.2`
* `io.spring:timestamp-batc-task:2.0.2`

and the Spring Boot 3.x versions are:
* `io.spring:timestamp-task:3.0.0`
* `io.spring:timestamp-batc-task:3.0.0`

**Comment by favna** [comment]
Alright thanks! Our migration has been blocked by https://github.com/spring-cloud/spring-cloud-task/issues/939 for quite some time now but I added a link to your reply on our Jira ticket so we can reference your response later. I'll close this issue for now.
