### ISSUE TITLE
401 Unauthorized while streaming with iris PA example

### ISSUE THREAD

**Issue by cinqs** [spring-cloud/spring-cloud-dataflow-samples#20]
Hi, I implemented iris PA example, and the stream is in deployed status.

while I do

    http post --target http://localhost:8080 --contentType application/json --data "{ \"sepalLength\": 6.4, \"sepalWidth\": 3.2, \"petalLength\":4.5, \"petalWidth\":1.5 }"

I got

```sh
 401 UNAUTHORIZED
```

```json
{
  "path" : "/",
  "error" : "Unauthorized",
  "message" : "Full authentication is required to access this resource",
  "timestamp" : 1484714522151,
  "status" : 401
}
```

While I used *Postman* with the `Basic Auth`

    username: user
    password: 0f9555a9-e5ae-448d-80c5-bcfc80acf7db

I still got the same problem.

    OS: debian:jessie
    SCDF: 1.1.1.RELEASE

**Comment by sabbyanandan** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-dataflow/issues/1130.
