### ISSUE TITLE
Add sample on how to use the test-binder for custom app development

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-samples#27]
In continuation to the [dev-marketing efforts](https://github.com/markpollack/spring-cloud-dataflow-samples/blob/dev-marketing/docs/src/main/asciidoc/stream-apps.adoc), as a developer, I'd like to add walkthrough guide on how to use the test-binder to develop and test custom applications.

**Comment by ericbottard** [comment]
PR is against @markpollack 's branch: https://github.com/markpollack/spring-cloud-dataflow-samples/pull/1
