### ISSUE TITLE
Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.IlegalArgumentException: Invalid TaskExecution, ID {15} not found

### ISSUE THREAD

**Issue by evasanthan** [spring-cloud/spring-cloud-dataflow-samples#31]
I just deployed as shared batch job sample in the Spring Data Flow where i could see the job ran and provided the exit code as zero but when i look at the debug statements which hasn't executed in the log file where it being thrown taskLifeCycleListener exception. Please help me to understand what could be a issue in PCF when deploying this sample program.

17-06-29T19:23:43.89+0530 [CELL/0] OUT Creating container
17-06-29T19:23:44.68+0530 [CELL/0] OUT Successfully created container
17-06-29T19:23:48.94+0530 [APP/TASK/simpletTask/0] OUT  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
17-06-29T19:23:48.94+0530 [APP/TASK/simpletTask/0] OUT  =========|_|==============|___/=/_/_/_/
17-06-29T19:23:48.95+0530 [APP/TASK/simpletTask/0] OUT  :: Spring Boot ::        (v1.5.2.RELEASE)
17-06-29T19:23:48.94+0530 [APP/TASK/simpletTask/0] OUT ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
17-06-29T19:23:48.94+0530 [APP/TASK/simpletTask/0] OUT   .   ____          _            __ _ _
17-06-29T19:23:48.94+0530 [APP/TASK/simpletTask/0] OUT   '  |____| .__|_| |_|_| |_\__, | / / / /
17-06-29T19:23:48.94+0530 [APP/TASK/simpletTask/0] OUT  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
17-06-29T19:23:49.09+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:49.093  INFO 7 --- [           main] pertySourceApplicationContextInitializer : Adding 'cloud' PropertySource to Appli
tionContext
17-06-29T19:23:49.20+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:49.204  INFO 7 --- [           main] io.spring.BatchJobApplication            : The following profiles are active: clo

17-06-29T19:23:49.20+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:49.204  INFO 7 --- [           main] io.spring.BatchJobApplication            : Starting BatchJobApplication on f11a42
-29c9-4fdb-acfa-43de5e286c8a with PID 7 (/home/vcap/app/BOOT-INF/classes started by vcap in /home/vcap/app)
17-06-29T19:23:49.31+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:49.314  INFO 7 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context
nnotation.AnnotationConfigApplicationContext@25f38edc: startup date [Thu Jun 29 13:53:49 UTC 2017]; root of context hierarchy
17-06-29T19:23:49.18+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:49.181  INFO 7 --- [           main] nfigurationApplicationContextInitializer : Adding cloud service auto-reconfigurat
n to ApplicationContext
17-06-29T19:23:49.85+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:49.859  INFO 7 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 't
nsactionManager' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=f
se; factoryBeanName=org.springframework.cloud.task.configuration.SimpleTaskConfiguration; factoryMethodName=transactionManager; initMethodName=null; destroyMethodName=(inferred); defined in
g.springframework.cloud.task.configuration.SimpleTaskConfiguration] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidat
true; primary=false; factoryBeanName=org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration; factoryMethodName=transactionManager; initMethodName=null; destroyMetho
ame=(inferred); defined in class path resource [org/springframework/batch/core/configuration/annotation/SimpleBatchConfiguration.class]]
17-06-29T19:23:50.25+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:50.258  INFO 7 --- [           main] urceCloudServiceBeanFactoryPostProcessor : Auto-reconfiguring beans of type javax
ql.DataSource
17-06-29T19:23:50.26+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:50.266  INFO 7 --- [           main] urceCloudServiceBeanFactoryPostProcessor : No matching service found. Skipping au
-reconfiguration.
17-06-29T19:23:50.29+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:50.293  WARN 7 --- [           main] o.s.c.a.ConfigurationClassEnhancer       : @Bean method ScopeConfiguration.stepSc
e is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostC
struct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.
17-06-29T19:23:50.31+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:50.315  WARN 7 --- [           main] o.s.c.a.ConfigurationClassEnhancer       : @Bean method ScopeConfiguration.jobSco
 is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostCo
truct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.
17-06-29T19:23:50.41+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:50.412  INFO 7 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.task.b
ch.configuration.TaskBatchAutoConfiguration' of type [org.springframework.cloud.task.batch.configuration.TaskBatchAutoConfiguration$$EnhancerBySpringCGLIB$$9003e312] is not eligible for gett
g processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
17-06-29T19:23:50.42+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:50.420  INFO 7 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.
notation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$a943786] is not eligible
or getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
17-06-29T19:23:50.46+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:50.462  INFO 7 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.task.b
ch.listener.BatchEventAutoConfiguration' of type [org.springframework.cloud.task.batch.listener.BatchEventAutoConfiguration$$EnhancerBySpringCGLIB$$d859ed15] is not eligible for getting proc
sed by all BeanPostProcessors (for example: not eligible for auto-proxying)
17-06-29T19:23:51.01+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.007 DEBUG 7 --- [           main] o.s.c.t.c.SimpleTaskConfiguration        : Using org.springframework.cloud.task.c
figuration.DefaultTaskConfigurer TaskConfigurer
17-06-29T19:23:51.25+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.250 DEBUG 7 --- [           main] o.s.c.t.r.s.TaskRepositoryInitializer    : Initializing task schema for h2 databa

17-06-29T19:23:51.25+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.257  INFO 7 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executing SQL script from class path r
ource [org/springframework/cloud/task/schema-h2.sql]
17-06-29T19:23:51.30+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.308  INFO 7 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executed SQL script from class path re
urce [org/springframework/cloud/task/schema-h2.sql] in 51 ms.
17-06-29T19:23:51.47+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.472  INFO 7 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executing SQL script from class path r
ource [org/springframework/batch/core/schema-h2.sql]
17-06-29T19:23:51.49+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.497  INFO 7 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executed SQL script from class path re
urce [org/springframework/batch/core/schema-h2.sql] in 25 ms.
17-06-29T19:23:51.60+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.605  INFO 7 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on
artup
17-06-29T19:23:51.61+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.611  INFO 7 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
17-06-29T19:23:51.69+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.690  INFO 7 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shu
own
17-06-29T19:23:51.69+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.692 ERROR 7 --- [           main] o.s.c.t.listener.TaskLifecycleListener   : An event to end a task has been receiv
 for a task that has not yet started.
17-06-29T19:23:51.69+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.690  WARN 7 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context i
tialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.IllegalArgument
ception: Invalid TaskExecution, ID 15 not found
17-06-29T19:23:51.70+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.700  INFO 7 --- [           main] utoConfigurationReportLoggingInitializer :
17-06-29T19:23:51.70+0530 [APP/TASK/simpletTask/0] OUT Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT 2017-06-29 13:53:51.720 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application startup failed
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.Il
galArgumentException: Invalid TaskExecution, ID 15 not found
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879) ~[spring-co
ext-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE

17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.
LEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.
7.RELEASE.jar!/:4.3.7.RELEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        ... 20 common frames omitted
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.
7.RELEASE.jar!/:4.3.7.RELEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spri
-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at io.spring.BatchJobApplication.main(BatchJobApplication.java:14) [classes/:na]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:na]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app/:na]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.util.Assert.notNull(Assert.java:134) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.cloud.task.listener.TaskLifecycleListener.doTaskStart(TaskLifecycleListener.java:200) ~[spring-cloud-task
ore-1.3.0.BUILD-SNAPSHOT.jar!/:1.3.0.BUILD-SNAPSHOT]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context
.3.7.RELEASE.jar!/:4.3.7.RELEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-
3.7.RELEASE.jar!/:4.3.7.RELEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT Caused by: java.lang.IllegalArgumentException: Invalid TaskExecution, ID 15 not found
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.cloud.task.listener.TaskLifecycleListener.start(TaskLifecycleListener.java:282) ~[spring-cloud-task-core-
3.0.BUILD-SNAPSHOT.jar!/:1.3.0.BUILD-SNAPSHOT]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-
3.7.RELEASE.jar!/:4.3.7.RELEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[spring-context-
3.7.RELEASE.jar!/:4.3.7.RELEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
17-06-29T19:23:51.72+0530 [APP/TASK/simpletTask/0] OUT        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app/:na]
17-06-29T19:23:51.75+0530 [APP/TASK/simpletTask/0] OUT Exit status 1
17-06-29T19:23:51.78+0530 [CELL/0] OUT Destroying container
17-06-29T19:23:52.98+0530 [CELL/0] OUT Successfully destroyed container

**Comment by sabbyanandan** [comment]
It is unclear what you're trying to do and the versions you're using. Without any information, it is hard to troubleshoot. Please share what you can from [this list](https://github.com/spring-cloud/spring-cloud-dataflow/wiki/Reporting-Issues).

**Comment by cppwfs** [comment]
Hello @ evasanthan. As a follow up note I see that you are using the H2 database.  In this case you will need to make sure your dataflow is configured properly as discussed here: http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.2.1.RELEASE/reference/htmlsingle/#getting-started.   The DataFlow server and tasks need to connect to the database service (as discussed in the link provided).

**Comment by evasanthan** [comment]
@sabbyanandan 


Spring Cloud Data Flow: 

Spring-cloud-dataflow-server-cloudfoundry-1.2.0.BUILD-SNAPSHOT	

Release version
Spring Cloud Data Flow: Spring-cloud-dataflow-shell-1.2.0.RELEASE

Release version
Pivotal Web service ( latest Trial account)

App Starters

https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/tasks/simple-batch-job

For custom apps, please also include Spring Boot and other dependency versions
Problem Description

I am just running the sample application which had shared in the same github code which is named as batch-job
https://github.com/spring-cloud/spring-cloud-dataflow-samples/tree/master/tasks/simple-batch-job

While we start this as a task in PCF , we are facing the taskLifeCycleListener issue.

Let me give the background, we are planning to create Spring Batch to execute some scheduled tasks in the cloud. We heard that Spring Data Flow is having additional
features to run the jobs and its takes care of task execution life cycle events. But when we run the sample program, getting a message like the job has been executed and failed state.
where logs says that the taskLifeCycleListener issue.  

Steps we have done :

1. batch job is exported to private repository
2. Registered with Spring data flow server
3. Created as a task (Not created any stream)
4. lauch the task

But we are getting "Exception encountered during context intialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.IllegalArgument
ception: Invalid TaskExecution, ID 15 not found"

**Comment by evasanthan** [comment]
@cppwfs 
Yes, I have configured mysql and Redis both services are bounded to the spring data flow.  should i need configure any database/this database service for deployed simple batch  job even it is not used any database connections?

**Comment by cppwfs** [comment]
Yes.  When a task  is launched from SCDF, SCDF records a task-execution-id for tracking and the task then uses this to record its task-execution information.   
Also include the dependency for mysql/mariadb to your sample task.

**Comment by evasanthan** [comment]
Thank you @cppwfs and @sabbyanandan to resolve this issue.  But i don't know that how to bind the datasource services rather than hardcoded user and password id even i bounded like **app.task-launcher-local.spring.cloud.deployer.cloudfoundry.services=mysqlPDF.**   which is also not picking up datasource connection while starting the server

Example :  

stream create foo --definition "triggertask --triggertask.uri= http://good.com/yyyy.jar --trigger.fixed-delay=180 --triggertask.environment-properties=**spring.datasource.url=jdbc:mysql://host/schema?user=xxxxx&password=yyyyy**,spring.datasource.maxActive=2,spring.datasource.tomcat.initial-size=2 | task-launcher-local"

And also restart option of task is disabled in spring data flow server by default.  I don't know that how batch program can be restarted pro grammatically or through spring data flow dash board.

On few blogs are mentioned like, Task-launcher-local app is for development purpose only. I'm not sure that what changes needs to be done for production implementation. Can i make use the same task-launcher-local for production purpose? please guide and help me on this as i am new to this technology.

**Comment by karthikitzmi** [comment]
I am having the similar issue. I am using MySQL in my SimpleTask application. I see SCDF creating task_execution table in MySQL. I believe its not inserting the records in MYSQL when the task in launched. So its unable to find  records. Here are the logs for SCDF. I expect it to be Database config issue.   Spring Cloud Data Flow Local Server  (v1.2.3.RELEASE)

2017-09-17 21:50:59.316  INFO 3888 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2017-09-17 21:51:00.705  WARN 3888 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/spring-cloud-dataflow-server-local/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2017-09-17 21:51:00.720  INFO 3888 --- [           main] o.s.c.d.s.local.LocalDataFlowServer      : No active profile set, falling back to default profiles: default
2017-09-17 21:51:05.784  INFO 3888 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2017-09-17 21:51:07.078  INFO 3888 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=b15ff760-91d3-31de-a2a8-f2cc5ce41a5c
2017-09-17 21:51:10.686  INFO 3888 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2017-09-17 21:51:10.691  INFO 3888 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.15
2017-09-17 21:51:10.995  INFO 3888 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-09-17 21:51:12.519  INFO 3888 --- [           main] erverConfiguration$H2ServerConfiguration : Starting H2 Server with URL: jdbc:h2:tcp://localhost:19092/mem:dataflow
2017-09-17 21:51:14.674  INFO 3888 --- [           main] o.s.c.d.s.r.s.DataflowRdbmsInitializer   : Adding dataflow schema classpath:schema-h2-common.sql for h2 database 2017-09-17 21:51:14.677  INFO 3888 --- [           main] o.s.c.d.s.r.s.DataflowRdbmsInitializer   : Adding dataflow schema classpath:schema-h2-streams.sql for h2 database


**Logs for the Task being launched:** 

2017-09-17 22:00:56.750  INFO 5496 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2017-09-17 22:00:56.800  WARN 5496 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.IllegalArgumentException: Invalid TaskExecution, ID 1 not found
2017-09-17 22:00:56.801  INFO 5496 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2017-09-17 22:00:56.802 ERROR 5496 --- [           main] o.s.c.t.listener.TaskLifecycleListener   : An event to end a task has been received for a task that has not yet started.
2017-09-17 22:00:56.826  INFO 5496 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-09-17 22:00:56.857 ERROR 5496 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.IllegalArgumentException: Invalid TaskExecution, ID 1 not found
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.11.RELEASE.jar!/:4.3.11.RELEASE]

**Comment by cppwfs** [comment]
I need a little context here. Are you launching the task from Spring Cloud Data Flow, a Task Launcher Sink or, Composed Task Runner.

**Comment by karthikitzmi** [comment]
I am launching the task from Spring cloud data flow. I registered my Application as a **task** using UI. Then gave a definition name. Launched the task application from tasks definitions in UI.

**Comment by cppwfs** [comment]
Can you send me a link to your repo for the SimpleTask

**Comment by karthikitzmi** [comment]
I am not sure If I could share the existing repo as its not public. I would appreciate if you could let me know on how to disable H2 DB on local server SCDF and enable Oracle DB that's being used by the SimpleTask. I got this issue when my SimpleTask was using oracle DB. I was able to run SimpleTask without DB interactions on local SCDF as that uses H2 internally.

I would give a try to setup OracleDB for SCDF local server if you could give some pointers.. If that doesn't work, I would recreate the issue with sample repo that is shareable.

**Comment by karthikitzmi** [comment]
I got it resolved. I had to add dependency jars for oracle in SCDF & launch it. Then this issue wasn't reproduced.

**Comment by sabbyanandan** [comment]
Thanks for confirming, @karthikitzmi.
