### ISSUE TITLE
Create initial batch ingest sample

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow-samples#35]
Create basic batch ingest sample

Use GS "Creating a Batch Service" (https://spring.io/guides/gs/batch-processing/) guide contents as a template for batch job.

* Read from a file, apply processing, write to database
* Hook in Spring Cloud Task
* Ensure job can be registered and executed through data flow
* Create README documenting build steps and how to register / launch the job as a task via Data Flow shell

**Comment by dturanski** [comment]
Merged
