### ISSUE TITLE
Create public-facing FTP server

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-samples#63]
child of spring-cloud/spring-cloud-dataflow-samples#61

**Comment by chrisjs** [comment]
Trevors recommendation is try setting something up in GCP free tier (but check any storage, transfer, etc limitations), re-use another instance we may have etc. So in short, we should allocate and manage this service.

**Comment by chrisjs** [comment]
this is setup, details stored offline.
